# Project: Scheduler
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = ../../Users/±Ë¡§¿±/AppData/Local/Temp/Temp1_base_code2.zip/project2_schedule/linkedList.o ../../Users/±Ë¡§¿±/AppData/Local/Temp/Temp1_base_code2.zip/project2_schedule/main.o ../../Users/±Ë¡§¿±/AppData/Local/Temp/Temp1_base_code2.zip/project2_schedule/schedule.o
LINKOBJ  = ../../Users/±Ë¡§¿±/AppData/Local/Temp/Temp1_base_code2.zip/project2_schedule/linkedList.o ../../Users/±Ë¡§¿±/AppData/Local/Temp/Temp1_base_code2.zip/project2_schedule/main.o ../../Users/±Ë¡§¿±/AppData/Local/Temp/Temp1_base_code2.zip/project2_schedule/schedule.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3 -s
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = project.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

../../Users/±Ë¡§¿±/AppData/Local/Temp/Temp1_base_code2.zip/project2_schedule/linkedList.o: ../../Users/±Ë¡§¿±/AppData/Local/Temp/Temp1_base_code2.zip/project2_schedule/linkedList.c
	$(CC) -c ../../Users/±Ë¡§¿±/AppData/Local/Temp/Temp1_base_code2.zip/project2_schedule/linkedList.c -o ../../Users/±Ë¡§¿±/AppData/Local/Temp/Temp1_base_code2.zip/project2_schedule/linkedList.o $(CFLAGS)

../../Users/±Ë¡§¿±/AppData/Local/Temp/Temp1_base_code2.zip/project2_schedule/main.o: ../../Users/±Ë¡§¿±/AppData/Local/Temp/Temp1_base_code2.zip/project2_schedule/main.c
	$(CC) -c ../../Users/±Ë¡§¿±/AppData/Local/Temp/Temp1_base_code2.zip/project2_schedule/main.c -o ../../Users/±Ë¡§¿±/AppData/Local/Temp/Temp1_base_code2.zip/project2_schedule/main.o $(CFLAGS)

../../Users/±Ë¡§¿±/AppData/Local/Temp/Temp1_base_code2.zip/project2_schedule/schedule.o: ../../Users/±Ë¡§¿±/AppData/Local/Temp/Temp1_base_code2.zip/project2_schedule/schedule.c
	$(CC) -c ../../Users/±Ë¡§¿±/AppData/Local/Temp/Temp1_base_code2.zip/project2_schedule/schedule.c -o ../../Users/±Ë¡§¿±/AppData/Local/Temp/Temp1_base_code2.zip/project2_schedule/schedule.o $(CFLAGS)
